name: flutter_space_data
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.3
  animated_text_kit: ^4.2.1
  rflutter_alert: ^2.0.4
  flutter_spinkit: ^5.1.0
  translator: ^0.1.7
#  desktop_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Doctor Glitch.otf
    - family: Autobus
      fonts:
        - asset: assets/fonts/Autobus.ttf
    - family: Baby Universe
      fonts:
        - asset: assets/fonts/Baby Universe.TTF
        - asset: assets/fonts/Baby Universe-Italic.TTF
          style: italic